#!/usr/bin/env bash
# Copy the desktop's contracts into this repository.
#
# `protocol/anodex-design.json` is generated by the desktop repo's
# `npm run design` and describes its palette, spacing, radii and icon glyphs.
# `DesktopContractTest` checks this app's hand-copied values against it, which
# is what turns a colour changed on the desktop and nowhere else from an
# invisible drift into a failing test here.
#
# The copy is a snapshot, deliberately: nothing fetches it automatically, so
# updating it is a commit somebody reviews, and the diff shows what moved on the
# other side before this app is changed to match.
#
# `protocol/anodex-protocol.json` is generated by the desktop's `npm run protocol`
# and describes every channel and every type that crosses the socket.
# `TurnResultContractTest` reads it to check that no field of a finished turn is
# arriving unaccounted for -- which is how `webSources` was sent for months and
# silently dropped here.
#
#     tools/sync-design-contract.sh [path-to-desktop-checkout]
set -euo pipefail

desktop="${1:-../Anodex4-next}"
here="$(dirname "$0")/.."

for name in anodex-design.json anodex-protocol.json; do
    source_file="$desktop/protocol/$name"

    if [ ! -f "$source_file" ]; then
        echo "no contract at $source_file" >&2
        echo "pass the desktop checkout as the first argument, or generate it there" >&2
        exit 1
    fi

    target="$here/protocol/$name"
    cp "$source_file" "$target"

    # `.gitattributes` pins these files to LF so the copy stays byte-identical to
    # the desktop's on Windows too. Without it git rewrites the line endings on
    # checkout and the two files differ in hundreds of places while agreeing on
    # every value, which makes "is this still the desktop's?" unanswerable by
    # comparing them.
    if ! cmp -s "$source_file" "$target"; then
        echo "warning: $name differs from the source byte for byte" >&2
    fi

    echo "copied $source_file"
done

echo "run ./gradlew :app:testDebugUnitTest --tests '*ContractTest*' to see what moved"
