#!/usr/bin/env bash
# Copy the desktop's design contract into this repository.
#
# `protocol/anodex-design.json` is generated by the desktop repo's
# `npm run design` and describes its palette, spacing, radii and icon glyphs.
# `DesktopContractTest` checks this app's hand-copied values against it, which
# is what turns a colour changed on the desktop and nowhere else from an
# invisible drift into a failing test here.
#
# The copy is a snapshot, deliberately: nothing fetches it automatically, so
# updating it is a commit somebody reviews, and the diff shows what moved on the
# other side before this app is changed to match.
#
#     tools/sync-design-contract.sh [path-to-desktop-checkout]
set -euo pipefail

desktop="${1:-../Anodex4-next}"
source_file="$desktop/protocol/anodex-design.json"

if [ ! -f "$source_file" ]; then
    echo "no design contract at $source_file" >&2
    echo "pass the desktop checkout as the first argument, or run 'npm run design' there" >&2
    exit 1
fi

cp "$source_file" "$(dirname "$0")/../protocol/anodex-design.json"
echo "copied $source_file"
echo "run ./gradlew :app:testDebugUnitTest --tests '*DesktopContractTest*' to see what moved"
